[google]
type = "service_account"
project_id = "dzmatch-votes-472309"
private_key_id = "ac052583ebdc33ad1eb6144c9e42ce100efadc52"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZHl8x4d/hhgy0
Wl8C7QQFXBeWxYZLCGVHwEg615mSyFY1Mf61BrCGn2p+Xr1LSXkA/CYmw8k52PwE
aodt+XKG1a+TO7lPh5KhUDkP4Jrmp0N2FU/GsT+0H5CWOITOqfUtK8EnlExBFnlY
Uqn9Ycu7iC1ZMq9999dod9meN4afvrmtpLn81luBBFQRZ6WlnHd3EPiZpHeQOA/T
X23wEHoFJpU4e1ieN0q5CwjIYeiBu62qWdKqcIZWVAYfHTsnRCIGaQ0MMEhno/RG
NV/cEV/JlH8XBI1HBk6MqfLzLsSm6GuFZHM4CXfDn+Wo5Uj6YHeyO8M2WBxrOTb7
p6XQrBgjAgMBAAECggEAAZ8WtvqDWmoG/Gnwk6Fa54ugHFKfJ3BBUk8w9J6P28QP
VaTf457cg7BwekIakw+GHoKNDOAJ43juwkU2he2cTt04bMC3J6Zx4Q9ua0KfoU2o
Izn6jEoYOJoU9+JFVcLq+7144Chr3kyUoGDPuAUvGR9KC6XDwfu75jlOrqQ74rko
H9zjTjO7z2GhdmuKvFkLqLEiXCS0N9k6IHq63P/DJ4sjybH81yvhOaO6jDXZuXzD
TK/U5wAJogq/w47AEPTrlDriT9GjH93dCq9svPBBad7ZVz4S3h8jnDKYnKcASpcp
MZJvALAgjStNRy84GgI6T+3gurGLEGi5Itd4g7aN8QKBgQDONOWkBDfJFX4nEkz4
175/oQdCyT2YEZslAJ/Hlyc1layX00CqvB7XE4Fiznz4WhLmRzLGilVqze0KRl3g
KjkfGQsyZRFGJzwGPxI3/SAubcf8WKLyAjXVPzBIROqonkvCMPY91dhQMGsB1ofW
Dgq6Vo3WZFfYXbOgx+EWcOklLQKBgQC+F7o6dOqOUei5JpKAlGcwAIj0DT4pzcHQ
X1fehDUy/EdU4UEfEcig06oKVTqKluFLpd7mMXcX0I+huk9bGLa1xtUri9fWK2Ju
McE/WE4FDAZYqHb18LVGpHQ0Lgo3eypjtfOHmRtNdcAo/bWBOa1p7yjjBM4wJq8R
kT8NF84kjwKBgDmXjIvCodIHrrQ66ESX/RyoXN7KVemjATHUesvD66+LnijJV8ZX
xEVNrVVrVnwGrECkognRmQm7efjkrlNtd4a39+ibUbfGPX2BIBWDHPnar4BLQTdW
ZrKoc1O7684sZ/xUsHGUyFWdMEXTJR0jzts8UWEPpXlIsmK1cKhT4MoBAoGBALAH
5vOVK1Qp87npR0d8peWkyS4/SS6LFIyyjftIML+LMT8f7R8pZ8HO4Kr66+BFAlL8
QmKmseNCxo98qVnxk9jXTLYrpO72dAsZVhwj2PQBg6r8LlVn12aYied8LwfbrZBy
gRczqD3d6dnLwBXv5G+yAgngfFPIrtw0xc+JGONvAoGADtaPXiIkRmr+Z+o3+pRS
+A+ua+X8LuiPvimmEyj6pInfyYL+i71eufkzGxdofvDvSFZCrt3Ww3S2h1GlVawY
rvVVFbogNsWEXzTPvuB6TOcx+oYK/rfohmMFDyGcS/+xtalYXk1lCghTWwDDSMCS
hXSYjOqHC/1zFTod4cRo39k=
-----END PRIVATE KEY-----"""
client_email = "votedzmatch@dzmatch-votes-472309.iam.gserviceaccount.com"
client_id = "110101641949621478669"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/votedzmatch%40dzmatch-votes-472309.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
